name: flutter_barcode_scanner
description: A plugin for barcode scanning support on Android and iOS. Supports barcodes, QR codes, etc.
version: 2.0.1
author: Amol Gangadhare <amol.gangadhare@gmail.com>
homepage: https://github.com/AmolGangadhare/flutter_barcode_scanner

environment:
  sdk: ^3.5.4
  flutter: 3.24.4

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.23

dev_dependencies:
  pedantic:
  test: ^1.16.8

flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.amolg.flutterbarcodescanner
        pluginClass: FlutterBarcodeScannerPlugin
      ios:
        pluginClass: SwiftFlutterBarcodeScannerPlugin
